<a href="https://colab.research.google.com/github/HyelinNAM/TIL/blob/master/0115_Pytorch_%EA%B8%B0%EB%B3%B8%ED%8A%9C%ED%86%A0%EB%A6%AC%EC%96%BC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# https://tutorials.pytorch.kr/

In [0]:
#1. 시작하기

import torch

x = torch.empty(5,3)
print(x)

tensor([[4.6370e-36, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 2.8026e-45],
        [0.0000e+00, 1.1210e-44, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 0.0000e+00]])


In [0]:
x = torch.rand(5,3)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[0.3211, 0.4622, 0.4851],
        [0.6089, 0.8447, 0.6532],
        [0.9790, 0.5675, 0.5753],
        [0.5811, 0.2918, 0.4674],
        [0.9756, 0.9197, 0.5079]])


In [0]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [0]:
x = torch.tensor([[5,4],[3,2]])
print(x)

tensor([[5, 4],
        [3, 2]])


In [0]:
x.size()

torch.Size([2, 2])

In [0]:
# 2.연산
x = torch.rand(5,3)
y = torch.rand(5,3)

print(x)
print()
print(y)
print()
print(x+y)

tensor([[0.2574, 0.5454, 0.3703],
        [0.8682, 0.7261, 0.6678],
        [0.4384, 0.1517, 0.5448],
        [0.1068, 0.3342, 0.8934],
        [0.3876, 0.8031, 0.1862]])

tensor([[0.3870, 0.4826, 0.8262],
        [0.8001, 0.4943, 0.7784],
        [0.9088, 0.8783, 0.1167],
        [0.8005, 0.1502, 0.7089],
        [0.3769, 0.0987, 0.1983]])

tensor([[0.6444, 1.0281, 1.1966],
        [1.6683, 1.2204, 1.4462],
        [1.3471, 1.0300, 0.6614],
        [0.9073, 0.4843, 1.6023],
        [0.7646, 0.9018, 0.3845]])


In [0]:
print(torch.add(x,y))
print()
print(y.add_(x))

tensor([[0.6444, 1.0281, 1.1966],
        [1.6683, 1.2204, 1.4462],
        [1.3471, 1.0300, 0.6614],
        [0.9073, 0.4843, 1.6023],
        [0.7646, 0.9018, 0.3845]])

tensor([[0.6444, 1.0281, 1.1966],
        [1.6683, 1.2204, 1.4462],
        [1.3471, 1.0300, 0.6614],
        [0.9073, 0.4843, 1.6023],
        [0.7646, 0.9018, 0.3845]])


In [0]:
print(x)
print()
print(x[:,:1])

tensor([[0.2574, 0.5454, 0.3703],
        [0.8682, 0.7261, 0.6678],
        [0.4384, 0.1517, 0.5448],
        [0.1068, 0.3342, 0.8934],
        [0.3876, 0.8031, 0.1862]])

tensor([[0.2574],
        [0.8682],
        [0.4384],
        [0.1068],
        [0.3876]])


In [0]:
x = torch.randn(4,4)
print(x)
y = x.view(2,8)
print()
print(y)

tensor([[-0.5108,  0.1347, -1.9643, -1.1354],
        [ 0.4257, -0.6068,  0.2019,  0.9682],
        [ 1.1215, -0.1422, -0.5129,  0.6291],
        [-0.8601, -0.6094, -0.3991,  0.5072]])

tensor([[-0.5108,  0.1347, -1.9643, -1.1354,  0.4257, -0.6068,  0.2019,  0.9682],
        [ 1.1215, -0.1422, -0.5129,  0.6291, -0.8601, -0.6094, -0.3991,  0.5072]])


In [0]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.7140])
-0.7139708399772644


In [0]:
# 3.Numpy 배열로 변환하기

a = torch.ones(5)
print(a)

b = a.numpy()
print(b)

print(type(a))
print(type(b))

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'torch.Tensor'>
<class 'numpy.ndarray'>


In [0]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [0]:
import numpy as np

np.add(b,1,out=b)
print(a)
print(b)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


In [0]:
print(x)

tensor([-0.7140])


In [0]:
# CUDA

if torch.cuda.is_available():
  device = torch.device("cuda")
  y = torch.ones_like(x,device=device)
  x = x.to(device)
  z = x+y
  print(z)
  print(z.to("cpu",torch.double))

tensor([0.2860], device='cuda:0')
tensor([0.2860], dtype=torch.float64)


In [0]:
# Autograd
x = torch.ones(2,2,requires_grad=True)

print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [0]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [0]:
print(y.grad_fn)

In [0]:
z = y * y * 3
out = z
print(out)

out2 = z.mean()
print(out2)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


In [0]:
out = z.mean()

In [0]:
out.backward()

In [0]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [0]:
x = torch.randn(3,requires_grad=True)

print(x)
print()

y = x * 2

while y.data.norm() < 1000 :
  y = y * 2
  print(y)
  print(y.data.norm()) # L2 Norm. 제곱합 후 루트
  print()

print(y)

tensor([0.7952, 0.2778, 0.2609], requires_grad=True)

tensor([3.1809, 1.1110, 1.0435], grad_fn=<MulBackward0>)
tensor(3.5273)

tensor([6.3619, 2.2221, 2.0870], grad_fn=<MulBackward0>)
tensor(7.0546)

tensor([12.7238,  4.4441,  4.1740], grad_fn=<MulBackward0>)
tensor(14.1091)

tensor([25.4476,  8.8882,  8.3481], grad_fn=<MulBackward0>)
tensor(28.2182)

tensor([50.8951, 17.7764, 16.6961], grad_fn=<MulBackward0>)
tensor(56.4365)

tensor([101.7902,  35.5529,  33.3923], grad_fn=<MulBackward0>)
tensor(112.8730)

tensor([203.5805,  71.1058,  66.7846], grad_fn=<MulBackward0>)
tensor(225.7459)

tensor([407.1609, 142.2115, 133.5692], grad_fn=<MulBackward0>)
tensor(451.4919)

tensor([814.3219, 284.4231, 267.1384], grad_fn=<MulBackward0>)
tensor(902.9837)

tensor([1628.6438,  568.8461,  534.2768], grad_fn=<MulBackward0>)
tensor(1805.9674)

tensor([1628.6438,  568.8461,  534.2768], grad_fn=<MulBackward0>)


In [0]:
v = torch.tensor([0.1,1.0,0.0001],dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([2.0480e+02, 2.0480e+03, 2.0480e-01])


In [0]:
print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad():
  print((x**2).requires_grad)

True
True
False


In [0]:
# Neural net

import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):

  def __init__(self):
    super(Net,self).__init__()

    self.conv1 = nn.Conv2d(1,6,3)
    self.conv2 = nn.Conv2d(6,16,3)
    self.fc1 = nn.Linear(16*6*6,120)
    self.fc2 = nn.Linear(120,84)
    self.fc3 = nn.Linear(84,10)

  def forward(self,x):
    print("forward!")
    print(x.size())
    x = F.max_pool2d(F.relu(self.conv1(x)),(2,2))
    print(x.size())
    x = F.max_pool2d(F.relu(self.conv2(x)),2)
    print(f"전_x의 사이즈:{x.size()}")
    x = x.view(-1,self.num_flat_features(x))
    print(f"후_x의 사이즈:{x.size()}")
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = self.fc3(x)
    print("forward 완료!")
    return x

  def num_flat_features(self,x):
    print("num_flat_features!")
    print(f"x.size: {x.size()}")
    size = x.size()[1:]
    print(type(size))
    print(f"size: {size}")
    num_features = 1
    for s in size:
      print(s)
      num_features *= s

    print(f"num_features: {num_features}")
    return num_features
  
net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [0]:
#list(net.parameters())
params = list(net.parameters())
print(len(params))
print(params[0].size())

10
torch.Size([6, 1, 3, 3])


In [0]:
import torch

input = torch.randn(1,1,32,32)
out = net(input)
print(out)

forward!
torch.Size([1, 1, 32, 32])
torch.Size([1, 6, 15, 15])
전_x의 사이즈:torch.Size([1, 16, 6, 6])
num_flat_features!
x.size: torch.Size([1, 16, 6, 6])
<class 'torch.Size'>
size: torch.Size([16, 6, 6])
16
6
6
num_features: 576
후_x의 사이즈:torch.Size([1, 576])
forward 완료!
tensor([[ 0.0616, -0.0946, -0.0355,  0.0749,  0.0730,  0.0660, -0.0839,  0.0548,
          0.0621, -0.0103]], grad_fn=<AddmmBackward>)


In [0]:
net.zero_grad()
out.backward(torch.randn(1,10))

In [0]:
output = net(input)
target = torch.randn(10)
target = target.view(1,-1)
criterion = nn.MSELoss()

loss = criterion(output,target)
print(loss)

forward!
torch.Size([1, 1, 32, 32])
torch.Size([1, 6, 15, 15])
전_x의 사이즈:torch.Size([1, 16, 6, 6])
num_flat_features!
x.size: torch.Size([1, 16, 6, 6])
<class 'torch.Size'>
size: torch.Size([16, 6, 6])
16
6
6
num_features: 576
후_x의 사이즈:torch.Size([1, 576])
forward 완료!
tensor(1.2627, grad_fn=<MseLossBackward>)


In [0]:
# Backward()

x = torch.ones(2,2,requires_grad=True)
print(x)

y = x + 2
print(y)

print()
print(y.grad_fn)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)



In [0]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [0]:
print(x.grad)

None


In [0]:
z.size()

torch.Size([2, 2])

In [0]:
k=torch.tensor([[1,0.1],[10,0]])
print(k)
print(k.size())

tensor([[ 1.0000,  0.1000],
        [10.0000,  0.0000]])
torch.Size([2, 2])


In [0]:
z.backward(k)

In [0]:
print(x.grad)

tensor([[ 18.0000,   1.8000],
        [180.0000,   0.0000]])


In [0]:
# Neural net 2

import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):

  def __init__(self):
    super(Net,self).__init__()

    self.conv1 = nn.Conv2d(1,6,3)
    self.conv2 = nn.Conv2d(6,16,3)
    self.fc1 = nn.Linear(16*6*6,120)
    self.fc2 = nn.Linear(120,84)
    self.fc3 = nn.Linear(84,10)

  def forward(self,x):
    x = F.max_pool2d(F.relu(self.conv1(x)),(2,2))
    x = F.max_pool2d(F.relu(self.conv2(x)),2)
    x = x.view(-1,self.num_flat_features(x))
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = self.fc3(x)
    return x

  def num_flat_features(self,x):
    size = x.size()[1:]
    num_features = 1
    for s in size:
      num_features *= s
    return num_features
  
net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [0]:
input = torch.randn(1,1,32,32)
out = net(input)
print(out)

tensor([[ 0.0019,  0.0860,  0.0934, -0.0158,  0.0662, -0.0460,  0.0714,  0.0021,
          0.1830, -0.0512]], grad_fn=<AddmmBackward>)


In [0]:
net.zero_grad()
out.backward(torch.randn(1,10))

In [0]:
output = net(input)
target = torch.randn(10)
target = target.view(1,-1)
criterion = nn.MSELoss()

loss = criterion(output,target)
print(loss)

tensor(1.7560, grad_fn=<MseLossBackward>)


In [0]:
print(loss.grad_fn)
print(loss.grad_fn.next_functions[0][0])  # Linear
print(loss.grad_fn.next_functions[0][0].next_functions[0][0])  # ReLU

In [0]:
net.zero_grad()

print('conv1.bias.grad before backward')
print(net.conv1.bias.grad)

loss.backward()

print('conv1.bias.grad after backward')
print(net.conv1.bias.grad)

conv1.bias.grad before backward
tensor([0., 0., 0., 0., 0., 0.])
conv1.bias.grad after backward
tensor([ 0.0123,  0.0175, -0.0390,  0.0139, -0.0314, -0.0030])


In [0]:
import torch.optim as optim

optimizer = optim.SGD(net.parameters(),lr=0.01)

optimizer.zero_grad()
output = net(input)
loss = criterion(output,target)
loss.backward()
optimizer.step()